name: Deploy Frontend (Mock)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mock SSH Setup (skipped)
        run: echo "Skipping SSH setup in mock mode"

      - name: Mock Build and Deploy Frontend
        run: |
          echo "🚧 MOCK DEPLOYMENT IN PROGRESS"
          echo "cd ~/openai-speak-mate-frontend || exit 1"
          echo "make stop && make clean_all"
          echo "git pull origin master"
          echo "make docker_build && make docker_run_server"
          echo "✅ MOCK DEPLOY COMPLETED"
